wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1646428059
    t:
      1:
      - 2
      - 3
      - 5
      2:
      - 2
      - 3
      - 5
      3:
      - 2
      4: 3.8.10
      5: 0.12.11
      8:
      - 5
activation:
  desc: null
  value: relu
bin_size:
  desc: null
  value: 1
data_dir:
  desc: null
  value: /home/shush/groundhog/data/4grid_atac/complete/random_chop/i_3072_w_1
loss_fn:
  desc: null
  value: poisson
model_fn:
  desc: null
  value: conv_profile_all_base
num_epochs:
  desc: null
  value: 100
task_type:
  desc: null
  value: quant
window_size:
  desc: null
  value: 2048
