wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.33
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
    t:
      1:
      - 3
      - 5
      2:
      - 3
      - 5
      3:
      - 2
      - 3
      - 8
      4: 3.6.9
      5: 0.10.33
      8:
      - 5
conv_dropout:
  desc: null
  value:
  - 0.2
  - 0.2
  - 0.4
dense:
  desc: null
  value: 1024
drop_out:
  desc: null
  value: 0.5
filtN:
  desc: null
  value:
  - 300
  - 400
  - 500
kern:
  desc: null
  value:
  - 19
  - 9
  - 7
max_pool:
  desc: null
  value:
  - 20
  - 5
model:
  desc: null
  value: rb_global
rb_filter:
  desc: null
  value:
  - 4
  - 4
