wandb_version: 1

bin_size:
  value: 1
data_dir:
  value: /mnt/1a18a49e-9a31-4dbf-accd-3fb8abbfab2d/shush/4grid_atac/complete/peak_centered/i_2048_w_1
epochN:
  value: 30
l_rate:
  value: 0.004
loss_fn:
  value: multinomialnll_mse
model_fn:
  value: ori_bpnet
window_size:
  value: 2048
