wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.30
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0b3
    t:
      1:
      - 3
      - 5
      2:
      - 3
      - 5
      3:
      - 2
      4: 3.7.0b3
      5: 0.10.30
      8:
      - 5
bin_size:
  desc: null
  value: 128
crop:
  desc: null
  value: r_crop
data_dir:
  desc: null
  value: /mnt/1a18a49e-9a31-4dbf-accd-3fb8abbfab2d/shush/4grid_atac/complete/peak_centered/i_3072_w_1
l_rate:
  desc: null
  value: 0.001
loss_fn:
  desc: null
  value: poisson
model_fn:
  desc: null
  value: basenjimod
num_epochs:
  desc: null
  value: 100
rev_comp:
  desc: null
  value: true
window_size:
  desc: null
  value: 2048
